version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: nuget
    directory: /src/Likvido.EfCore.SqlServerContextFactory
    schedule:
      interval: daily
