name: Publish to nuget

on:
  push:
    branches:
      - main
    paths:
      - src/version.props
      - .github/workflows/nuget.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Build binaries
        run: dotnet build -c Release src/Likvido.EfCore.SqlServerContextFactory/Likvido.EfCore.SqlServerContextFactory.csproj

      - name: Creating a package
        run: dotnet pack --no-build -c Release src/Likvido.EfCore.SqlServerContextFactory/Likvido.EfCore.SqlServerContextFactory.csproj -o .

      - name: Publish to Nuget
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate -n
